[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_COLOR_16_SWAP=1
    -DLV_TICK_CUSTOM=1
board_build.filesystem = littlefs

lib_deps =
    m5stack/M5Unified@^0.1.17
    m5stack/M5GFX@^0.1.17
    someweisguy/esp_dmx@^3.1.0
    lvgl/lvgl@^8.3.11
